services:
  - type: web
    name: django-todo
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Todo.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12